const mongoose = require('mongoose');

const JournalDataShema = new mongoose.Schema({
    Sr_No :String,
    Academic_Year:String,
    Department:String,
    Name_1:String,
    Name_2:String,
    Department:String,
    Organization: String,
    Name_3: String ,
    Name_4:String,
    // Conference_Book: String,
    Title_of_Research_Paper : String,
    International_National : String,
    Title:String,
    Publisher:String,
    UGC_enlistment:String,
    Publication_date:String,
    Month:String,
    Year:String,
    Volumn:String,
    Number:String,
    Pages:String,
    DOI:String,
    ISSN_P:String,
    ISSN_O:String,
    F_value:String,
    F_year:String,
    F_Agency:String,
    // proceedings_conference : String,
    // Start_Date:String,
    // End_Date:String,
    // Name:String,
    // Organizer:String,
    // City:String,
    // State:String,
    // Country:String,
    // Name_of_Publisher : String,
    // Publication_Date:String,
    // Pages:String,
    // DOI:String,
    // Processing : String,
    // institue: String,
})

const JournalDataModel = new mongoose.model("journalData", JournalDataShema);

module.exports ={ JournalDataModel };